### ISSUE TITLE
Dummy tests are not controller tests

### ISSUE THREAD

**Issue by aprofeit** [activemerchant/payment_icons#1]
`IconControllerTest` does not test any controller. These should not be controller tests.

https://github.com/activemerchant/payment_icons/blob/master/test/dummy/test/controllers/icons_controller_test.rb

**Comment by nakulpathak3** [comment]
Hey I updated the tests but forgot to comment here. Can you have a look at the current [tests] (https://github.com/activemerchant/payment_icons/blob/master/test/dummy/test/controllers/icons_controller_test.rb) and let me know if we can close this or not?

**Comment by NathanPJF** [comment]
I'm closing this, but feel free to reopen if it's still an issue someone wants to take on.
