### ISSUE TITLE
Need to update SVG

### ISSUE THREAD

**Issue by smahendiran** [activemerchant/payment_icons#1088]
remote: Permission to activemerchant/payment_icons.git denied to smahendiran.

Do I need to get permission to push changes into my branch.
Whom to contact to push the changes.

**Comment by Jacquesattaque** [comment]
@smahendiran You submit a PR to this repo and we approve and merge.

**Comment by smahendiran** [comment]
@Jacquesattaque 
I'm unable to push the changes into the branch.

![image](https://github.com/activemerchant/payment_icons/assets/105439430/84dd3d2d-5510-4909-af09-3b13d7e7526a)

**Comment by Jacquesattaque** [comment]
@smahendiran We do a monthly release of these icons. The next release is tentatively scheduled for next Wednesday, November 1.

**Comment by smahendiran** [comment]
Sorry @Jacquesattaque . Issue is resolved now.
