### ISSUE TITLE
Add Bancomat Pay Icon

### ISSUE THREAD

**Issue by sebastian-mollie** [activemerchant/payment_icons#1142]
Bacomat pay is one of the biggest payments in Italy. Would it be possible to add this payment method and icon? 

https://bancomat.it/it/bancomat/bancomat-pay%C2%AE

**Comment by adeniyiao** [comment]
Hi @sebastian-mollie , you can do this by creating a PR and submitting a new icon using this guide https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md

**Comment by adeniyiao** [comment]
Closing as this is available as per https://github.com/activemerchant/payment_icons/pull/1151

![image](https://github.com/activemerchant/payment_icons/assets/97685764/b4f60bce-5789-46c2-845f-6a1630d8b98b)
