### ISSUE TITLE
Colombia Payments method

### ISSUE THREAD

**Issue by jhaiver** [activemerchant/payment_icons#1173]
Icons do not appear for payment methods that are very important and common in Colombia: Wompi, Efecty, QR Bancolombia, Nequi, Daviplata, and cash payments through Banking Correspondents. Thank you
![IMG_9044](https://github.com/activemerchant/payment_icons/assets/24641171/73072b82-03e6-41aa-897e-417656936092)
![Wompi_LogoPrincipal](https://github.com/activemerchant/payment_icons/assets/24641171/162193ee-39f3-43cc-91ee-daebc19d9e8e)
![IMG_9046](https://github.com/activemerchant/payment_icons/assets/24641171/4910a1e3-3acf-4326-9828-88620feac750)
![daviplata](https://github.com/activemerchant/payment_icons/assets/24641171/82ffffe6-a37d-46ad-ae57-ba5f915af814)
![bancolombia](https://github.com/activemerchant/payment_icons/assets/24641171/27ac4da5-5328-4377-87ba-be90be8b3342)

**Comment by Lovedanihonjin** [comment]
@jhaiver Thank you for bringing this to our attention. You can submit a PR with the appropriate payment method icons. Please find the contribution guidelines [here](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md).
