### ISSUE TITLE
Float Payments Icon not displaying correctly

### ISSUE THREAD

**Issue by BradleyGoulding** [activemerchant/payment_icons#1178]
We updated the icon for Float Payments approximately 3 weeks ago with PR #1166, however the icon when added to our payments app does not display at all.

![Screenshot 2024-05-06 at 17 10 49](https://github.com/activemerchant/payment_icons/assets/4862180/0b2b18ba-b8bf-44da-8465-e0967484d920)

however the file displays correctly in github for example

![Screenshot 2024-05-06 at 17 10 58](https://github.com/activemerchant/payment_icons/assets/4862180/041abf3a-cf60-4bd2-af54-e7cd91811b90)

If i inspect the element that is not displaying in the first screenshot, I get the url here [https://cdn.shopify.com/shopifycloud/partners-web-platform/partners-dashboard/52b622c5c523a41ae25d.svg](https://cdn.shopify.com/shopifycloud/partners-web-platform/partners-dashboard/52b622c5c523a41ae25d.svg)

It appears to be loading correctly and with the correct content type.

I am not sure what the way forward to fix this is.

**Comment by BradleyGoulding** [comment]
Any feedback available?

**Comment by adeniyiao** [comment]
Hi @BradleyGoulding , Looks like the SVG is missing some attributes noticeably `xmlns="http://www.w3.org/2000/svg"`, so you will need to submit PR with an updated icon with the attributes as per this [template](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md#template)

**Comment by BradleyGoulding** [comment]
Hi @adeniyiao, thank you for your feedback. I have made the required change and opened the PR #1193

**Comment by adeniyiao** [comment]
Closing as icon is showing correctly now

![image](https://github.com/activemerchant/payment_icons/assets/97685764/4af2cda4-5818-4493-b202-1afe8362b379)
