### ISSUE TITLE
supported_payment_methods: Following payment methods not permitted

### ISSUE THREAD

**Issue by alfaro28** [activemerchant/payment_icons#1199]
Hi, I just had my icon merged and released on release v1.7.43, however when deploying a new version with the cli I get the following error

```
Validation errors                                                                                                                   │
│    • supported_payment_methods: Following payment methods ["bancoazteca"] not permitted    
```

How long does it take for me to be able to update my payment method with the new icon? or am I doing something wrong?

**Comment by adeniyiao** [comment]
Hi @alfaro28 could you please check again and confirm if this is resolved

**Comment by alfaro28** [comment]
Yeah, the issue was resolved after a few days
