### ISSUE TITLE
Query regarding a "generic" bank icon

### ISSUE THREAD

**Issue by captn3m0** [activemerchant/payment_icons#12]
We at Razorpay support over 50 Banks for online payments. (This is aside from the cards). As such, adding logos for all these 50 banks is clearly useless.

On our checkout form, we tackle this by showing the 6 most common banks [[demo]](https://razorpay.com/demo/):

![image](https://cloud.githubusercontent.com/assets/584253/14420947/812f1cdc-ffec-11e5-825d-aaca0acf7519.png)

However, since customers coming from Shopify are more likely to recognize the card logos, we were wondering if it makes sense to add a generic "netbanking icon". We did a mockup for the same, and I'd file a PR if it sounds reasonable:

![bank](https://cloud.githubusercontent.com/assets/584253/14421234/20c35afa-ffee-11e5-841b-1a57ba4745d3.png)

The entry in `payments_icon.yml` could read:

```yml
-
  name: netbanking
  label: NetBanking
  group: bank_transfers
```

**Comment by andrewpaliga** [comment]
@captn3m0 this sounds reasonable -- logo looks good!
