### ISSUE TITLE
JCB icon may be too minimalistic

### ISSUE THREAD

**Issue by larouxn** [activemerchant/payment_icons#122]
Unlike their official icon:
![logo_03](https://user-images.githubusercontent.com/1557529/44942461-5719dd00-adec-11e8-96a8-81ab57d832d7.gif)

[the icon](https://github.com/activemerchant/payment_icons/blob/b59e7ce2aefbaf094b841a9beb55d6b8f543e8e0/app/assets/images/payment_icons/jcb.svg) provided in this repo:
![this_repo_logo](https://user-images.githubusercontent.com/1557529/44897033-48242380-ad35-11e8-8f48-3f826dbd69c6.png)

is somewhat nondescript, only containing the coloured bands but not the `JCB`. People outside of Japan and/or those not super familiar with JCB may not recognize the logo provided in here.

**Comment by larouxn** [comment]
Maybe we could upgrade it something like [this logo](https://github.com/gregoiresgt/payment-icons/blob/919d90075e88275a0f8d324788bd0ed33b667956/Assets/Credit%20Card/JCB/JCB-card-light.svg)?
![jcb-card-light](https://user-images.githubusercontent.com/1557529/44969408-11921700-af88-11e8-8a37-71d01dd0d588.png)

**Comment by NathanPJF** [comment]
I believe it was @vernalkick knows the history of these minimalistic icons.

**Comment by vernalkick** [comment]
I like what @larouxn is proposing 👌

**Comment by alekmackie** [comment]
Alright, I've got a couple of options for us to consider: 
[jcb.zip](https://github.com/activemerchant/payment_icons/files/2358164/jcb.zip)

In both options, I've changed the colours of each band to match those in the legit JCB logo.  I think we should respect JCB's brand colours, but it also bumps up the contrast with the white text.  It helps to make the text more legible at such a small size.

`jcb-01`: JCB text with the closest match font I could find, slightly modified to match even more.  
`jcb-02`: JCB text that I created to try to stay true to JCB's font, but modified to make it more legible at the small size.  

<img width="919" alt="screen shot 2018-09-06 at 10 51 50 am" src="https://user-images.githubusercontent.com/5382363/45175812-1bec2500-b1c3-11e8-9419-4754fea7e9fd.png">

Any thoughts?  Be sure to take a look at the SVGs in the ZIP file to get a sense of how it works at the size it will be displayed!

**Comment by larouxn** [comment]
I initially preferred `jcb-02` but upon viewing them both at 60x39 resolution, `jcb-01` certainly seems more legible to me. I vote for `jcb-01`. Open to counterpoints though.
![test](https://user-images.githubusercontent.com/1557529/45196429-2972df00-b297-11e8-9780-3533c4735a96.gif)

**Comment by vernalkick** [comment]
<img width="498" alt="screen shot 2018-09-07 at 10 08 55 am" src="https://user-images.githubusercontent.com/1269855/45229013-c121fe80-b292-11e8-9b3a-bc76c5ccef03.png">

Great work! I took `jcb-01` and tweaked it a bit to be bigger and to match more closely the original logo (taking bits from `02`). I also aligned things to the pixel grid as much as possible.

Here's a link to the updated SVG mark: [jcb-01-modified.svg.zip](https://github.com/activemerchant/payment_icons/files/2361645/jcb-01-modified.svg.zip)

**Comment by larouxn** [comment]
I love this modified `jcb-01`. It's beautiful _and_ functional.

**Comment by alekmackie** [comment]
LGTM! :shipit:

**Comment by larouxn** [comment]
PR is up! https://github.com/activemerchant/payment_icons/pull/125
