### ISSUE TITLE
Missing icon for solo CC

### ISSUE THREAD

**Issue by christianblais** [activemerchant/payment_icons#13]
There is currently no icon for solo credit cards.

**Comment by andrewpaliga** [comment]
@ThereExistsX can you take look? It looks like we have the icon in Shopify just a matter of uploading it to his repo. https://github.com/Shopify/shopify/blob/master/app/assets/svg/admin/payment-solo-small.svg

**Comment by ThereExistsX** [comment]
Solo is being removed from Shopify see -- https://github.com/Shopify/shopify/issues/72495
