### ISSUE TITLE
Apple Pay icon color

### ISSUE THREAD

**Issue by shawnr42** [activemerchant/payment_icons#138]
The icon for Apple Pay does not have any colours in it for the border, Apple logo, or the text, so it inherits the colour from the page. For example on Shopify's Debut theme if the footer text colour is blue, the icon appears blue.

![https://screenshot.click/08-41-w7am7-fq7d5.png](https://screenshot.click/08-41-w7am7-fq7d5.png)

This happens in other websites as well unless the icon has a specific colour applied to it, the icon will be whatever colour the surrounding text is.

**Comment by NathanPJF** [comment]
Thanks for making this issue @shawnr42 

I checked the SVG and see that it never specifies any `fill` values for its paths. The Apple Pay icon in this repo should be doing that to safeguard against situations like this.

**Recommended fix**: put `fill="#000"` on all the appropriate paths.
