### ISSUE TITLE
rails-4-2.gemfile failing, cannot find `bundler (< 2.0, >= 1.3.0)`

### ISSUE THREAD

**Issue by NathanPJF** [activemerchant/payment_icons#149]
## Issue 

Travis CI tests have begun consistently failing for tests related to `rails-4-2.gemfile`. 

Here is an example output that shows `bunder (2.0.1)` is being used and that a version of `bundler (< 2.0, >= 1.3.0)` cannot be found.

<details><summary>Out from failing test</summary>

```bash
adding /home/travis/build/activemerchant/payment_icons/gemfiles/vendor/bundle to cache
creating directory /home/travis/build/activemerchant/payment_icons/gemfiles/vendor/bundle
ruby.versions
$ ruby --version
ruby 2.3.7p456 (2018-03-28 revision 63024) [x86_64-linux]
$ rvm --version
rvm 1.29.3 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]
$ bundle --version
Bundler version 2.0.1
$ gem --version
2.6.14
37.98s$ bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "bundler":
  In rails-4-2.gemfile:
    rails (~> 4.2.0) was resolved to 4.2.11, which depends on
      bundler (< 2.0, >= 1.3.0)
  Current Bundler version:
    bundler (2.0.1)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?
Could not find gem 'bundler (< 2.0, >= 1.3.0)', which is required by gem 'rails
(~> 4.2.0)', in any of the sources.
Bundler could not find compatible versions for gem "rails":
  In rails-4-2.gemfile:
    rails (~> 4.2.0)
    payment_icons was resolved to 1.0.4, which depends on
      rails (< 6.0, >= 4.1)
The command "eval bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle} " failed. Retrying, 2 of 3.
```

</details>
&nbsp;

Example tests: 
* Pull Request #147 add dash and eos icons: https://travis-ci.org/activemerchant/payment_icons/jobs/475771567
* Pull Request #148 Adding enets icon : https://travis-ci.org/activemerchant/payment_icons/jobs/476712689

These tests were passing as recently as Dec 21st when this PR was merged https://github.com/activemerchant/payment_icons/pull/146.  The failing tests might be related to the release of Bundler 2.0 on Jan 4th, 2019: https://bundler.io/blog/2019/01/04/an-update-on-the-bundler-2-release.html

@maximevaillancourt @pi3r I'm not sure how to resolve this issue, would you be able to take a look?

### Other questions

The command to test for `rails-4-2` is defined in the [`.travis.yml` file](https://github.com/activemerchant/payment_icons/blob/master/.travis.yml#L12).  However, I'm not sure why we need to be testing in this version of Rails.  Is it safe to remove?

**Comment by NathanPJF** [comment]
Assigning @unixcharles :)

**Comment by bdewater** [comment]
I checked in the services DB which apps use this gem, they all use Rails 5.2 or higher so we can drop testing older versions IMO.

**Comment by unixcharles** [comment]
I don't mind fixing it if you can add me to the collaborators.
