### ISSUE TITLE
Test for <image> and <img> tags with a URL path

### ISSUE THREAD

**Issue by NathanPJF** [activemerchant/payment_icons#174]
## Issue

In our [contributing guidelines](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md#markup) we say that submissions cannot include `<image>` or `<img>` tags. The point is to prevent element where the `xlink:href` resolves to a filepath.  Example : `<image xlink:href="path/to/file.svg">`

However, we don't have a unit test to automatically check this, which means repo maintainers need to visually check optimized SVG code to spot them.

Example commit on a PR: https://github.com/activemerchant/payment_icons/pull/165/commits/a2b7fa8b95cd1a6e17623842cdbf7a250cb35ae8

This was caught by @tauthomas01 in https://github.com/activemerchant/payment_icons/pull/165#issuecomment-474482483, but ideally this would be automatically done.

### Why do we prevent these?

We don't want `<img>` or `<image>` tags that create external dependencies. In the [referenced commit](https://github.com/activemerchant/payment_icons/pull/165/commits/a2b7fa8b95cd1a6e17623842cdbf7a250cb35ae8), it is looking for a file path.  This will create two scenarios:

1. The file is never found, so there is an error. [Screenshot example here](https://screenshot.click/19-20-dsvo5-pnrn3.jpg)
2. The file is found and it becomes part of the icon's design. Which means the icon could change unexpectedly if the image at that file path ever changes.

### When are `<image>` and `<img>` okay?

We have a [number of icons that use the `<image>` tag](https://github.com/activemerchant/payment_icons/search?q=image+path%3Aapp%2Fassets%2Fimages%2Fpayment_icons%2F&unscoped_q=image+path%3Aapp%2Fassets%2Fimages%2Fpayment_icons%2F), however, the `link:href` is base64 encoded which is okay.

@maximevaillancourt Would you happen to have spare cycles to help us out with this? 

## Additional notes

Our [contributing guidelines](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md#markup) we say that submissions cannot include `<image>` or `<img>` tags - but this is too simplistic. We accept `<image>` tags provided that the `link:href` is base64 encoded.

**Comment by NathanPJF** [comment]
cc @tauthomas01

**Comment by maximevaillancourt** [comment]
Looking into it now.
