### ISSUE TITLE
Seven Eleven icon is outdated

### ISSUE THREAD

**Issue by larouxn** [activemerchant/payment_icons#187]
The Seven Eleven icon has changed a bit. We should update it accordingly.

Current Seven Eleven icon [SVG](https://github.com/activemerchant/payment_icons/blob/master/app/assets/images/payment_icons/seveneleven.svg). (this repo)
Latest Seven Eleven icon [SVG](https://ja.wikipedia.org/wiki/%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB:Seven_eleven_logo.svg). (Wikipedia)

We can _probably_ fit this new one within our original green rectangle. Definitely looks like it'll be a bit of a challenge though.

Note, it seems new logo may be Japan specific. We may need to create a new `sevenelevenjapan.svg` logo... unless we see this icon's usage as Japan specific. Then we can just update it.

**Comment by larouxn** [comment]
In my research, I have been unable to find any countries with an equivalent 7/11 based "konbini" payment system.

In that case, given the 7/11 logo along with the Lawson, FamilyMart, and so on convenience store logos _are_ just used for Japanese convenience store payments, I think we're safe to proceed with updating the 7/11 logo to the new Japan specific 7/11 logo.

**Comment by tauthomas01** [comment]
Hi @larouxn ,

Thank you for making an issue. Do you know if someone is in need to use the new icon?

**Comment by larouxn** [comment]
Hello @tauthomas01, I've heard from one Japanese company, GMO Epsilon, that the icon is outdated but I'm still confirming with them what the situation is. I will report back here when I have more details.

**Comment by larouxn** [comment]
This no longer seems necessary. 🙌
