### ISSUE TITLE
iDEAL payment icon does not output in footer when activated via Shopify Payments

### ISSUE THREAD

**Issue by gearoidmct** [activemerchant/payment_icons#190]
### **Problem:**
The iDEAL payment method icon does not appear in the footer alongside other icons when enabled via Shopify Payments.

A full-color SVG is available for this icon [here](https://github.com/Shopify/shopify/blob/master/app/assets/images/global/payment_types/creditcards_ideal.svg).

### **Scope**
Any theme using the `payment_type_svg_tag` liquid tag.
 
### **Example**
The following Dutch store has iDEAL enabled via Shopify Payments in Payments section: 

Payments section: https://eviakussens.myshopify.com/admin/settings/payments

[![alt](https://screenshot.click/04-17-bhsia-5jffj.png)](https://screenshot.click/04-17-bhsia-5jffj.png)

Storefront: https://eviakussens.nl

icon is not present in both footer or code:
[![alt](https://screenshot.click/04-45-4vq8e-9zqdn.png)](https://screenshot.click/04-45-4vq8e-9zqdn.png)

### **Expected vs Actual**
_Expected_ - Would expect to see iDEAL payment method icon in footer since it is present with other payment method icons in Shopify Payments section.
_Actual_ - iDEAL payment method appears in admin but not storefront.

**Comment by tauthomas01** [comment]
Hi @gearoidmct , I created an issue on Shopify's core since the problem is more aimed towards that instead of payment icons repo.

**Comment by gearoidmct** [comment]
Issue recreated here: https://github.com/Shopify/shopify/issues/206510
