### ISSUE TITLE
Add Ruby 2.4 in Travis CI

### ISSUE THREAD

**Issue by tauthomas01** [activemerchant/payment_icons#217]
### Problem

There has been some difficulties making releases and make the build pass during CI integration. One attempt to solve the problem was to downgrade the [`sassc version`](https://github.com/activemerchant/payment_icons/pull/212) but the issue is still persisting.

For the time being, Ruby 2.4 will be removed from Travis CI in order to get `master` error-free and working with 2.5 should be the priority.

### More information

From the history of builds, only in Ruby `2.4` doesn't pass, otherwise other Ruby versions (2.5.1, 2.6.2) are passing.

@SebastianSzturo @AnotherJoSmith @rafaelfranca @unixcharles

**Comment by larouxn** [comment]
Support for Ruby 2.4 ended in April of this year ([blog](https://www.ruby-lang.org/en/news/2020/04/05/support-of-ruby-2-4-has-ended/)).

For additional context, Travis CI Rubies were last update in https://github.com/activemerchant/payment_icons/pull/322. (Ruby 2.5, 2.6. 2.7)

**Comment by larouxn** [comment]
Closing as Ruby 2.4 is no longer supported.
