### ISSUE TITLE
Psych error

### ISSUE THREAD

**Issue by bgentry** [activemerchant/payment_icons#27]
I'm getting this on the current master:

```
Psych::SyntaxError: (<unknown>): did not find expected '-' indicator while parsing a block collection at line 1 column 1
from /Users/bgentry/.rbenv/versions/2.3.3/lib/ruby/2.3.0/psych.rb:379:in `parse'
```

A search indicates that it has to do with weird YAML whitespace. This line in particular stands out as having an extra space at the start: https://github.com/activemerchant/payment_icons/blob/master/db/payment_icons.yml#L145

If I revert to commit 6f8a9049948057ed693cf536573a268822a1c37e, things work without error.

**Comment by bdewater** [comment]
Should be fixed by #30 :)
