### ISSUE TITLE
Related to Payment Icon

### ISSUE THREAD

**Issue by Sanjeev-Gupta** [activemerchant/payment_icons#28]
Hi,

I have a Payment Gateway whose Payment Icon I submitted to Shopify GIT Repository on branch "laybuy" at https://github.com/Sanjeev-Gupta/payment_icons.git. I want this icon to list as Payment Icon for my payment method on Shopify.

I uploaded it about 2 weeks ago, and no reply from Shopify. Can you please tell me what to do and how to track its processing ?

**Comment by bdewater** [comment]
Hey, sorry for the late reply. It looks like you've committed to your fork (`Sanjeev-Gupta/payment_icons`) but did not open a pull request to this repository (`activemerchant/payment_icons`). For more information, see https://help.github.com/articles/creating-a-pull-request/. Once you've opened a pull request, you can easily see if and when your contribution is merged.

**Comment by AnthonyClark** [comment]
Hey @Sanjeev-Gupta, please open a Pull Request as described above. Let us know if you're still having trouble with it.
