### ISSUE TITLE
Change d-barai icon

### ISSUE THREAD

**Issue by iwasakis** [activemerchant/payment_icons#352]
Hi @larouxn 
I actually found that the current d-barai icon, changing original aspect ratio, is prohibited alterations.
Would you please use <img width="30" alt="dbarai" src="https://user-images.githubusercontent.com/5648031/94289636-48fe0280-ff59-11ea-984a-907c236d4475.png">,with complying isolaton policy here?
<img width="277" alt="Isolation policy" src="https://user-images.githubusercontent.com/5648031/94289727-6fbc3900-ff59-11ea-9bbf-8dbd86135334.png">

Thanks!

**Comment by larouxn** [comment]
👋 @iwasakis, do you have an SVG we can use for the `d払い` icon?

**Comment by iwasakis** [comment]
@larouxn here you go!
[dbaraCMYK.zip](https://github.com/activemerchant/payment_icons/files/5285011/dbaraCMYK.zip)

**Comment by yishus** [comment]
![d_barai](https://user-images.githubusercontent.com/5773874/94398176-a8495600-0197-11eb-9ac8-fe434a07c428.png) (original)
![d_barai@4x](https://user-images.githubusercontent.com/5773874/94398229-c44cf780-0197-11eb-8a94-7239b63f1ee8.png) (4x)

👋 @iwasakis Thanks for sending over the svg file! We've updated the icon according to the aspect ratio above, I hope this works 👍

**Comment by iwasakis** [comment]
Perfect, thanks!

**Comment by larouxn** [comment]
👋 @iwasakis, the `d払い` icon in the gem has not be updated yet. We will comment here and close the issue when it's been merged and released in a new version of the gem so you know when it's available. 🙇‍♂️
