### ISSUE TITLE
Gem getting heavier

### ISSUE THREAD

**Issue by larouxn** [activemerchant/payment_icons#407]
According to [rubygems.org/gems/payment_icons/versions](https://rubygems.org/gems/payment_icons/versions), the gem has gotten quite a bit heavier recently. May be due tot he addition of several base64 png encoded icons as many were added in https://github.com/activemerchant/payment_icons/pull/393 and released as party of v1.5.7.
<img width="276" alt="Screen Shot 2021-02-08 at 13 42 07" src="https://user-images.githubusercontent.com/1557529/107176718-7f718100-6a13-11eb-8299-d83711bb1590.png">

**Comment by tauthomas01** [comment]
I noticed as well lately that many merged PRs were using base64 png icon, which I have concerns. Should we enforce to use proper SVG tags (`<circle>`, `<path>`...) instead of base64 png format?

**Comment by larouxn** [comment]
Hmm, SVG only would certainly cut down on size but there are definitely icons for which people won't be able to find SVGs. 🤔

That said, considering this size increase is from just 10-20 recent icons I think we need to aim to enforce SVG only going forward.
