### ISSUE TITLE
Payment Icon Request - Payflex

### ISSUE THREAD

**Issue by TomLister21** [activemerchant/payment_icons#411]
We would like to get a payment icon for our payment gateway - Payflex.

We need this so we can be added as a recognized payment gateway with Shopify. 

Logos for the icon can be found here [https://widgets.payflex.co.za/]

**Comment by larouxn** [comment]
👋 Hey @TomLister21, would you be able to be able to open a pull request for the Payflex icon? ([Guide](https://github.com/activemerchant/payment_icons/blob/78bea12a0918509852d790d867d8401a4a718ec4/CONTRIBUTING.md))

**Comment by TomLister21** [comment]
Thanks @larouxn , we will do that. 👍

**Comment by larouxn** [comment]
Looks like Payflex icon was added in https://github.com/activemerchant/payment_icons/pull/418 and updated in https://github.com/activemerchant/payment_icons/pull/490.
