### ISSUE TITLE
Request to add new payment icons

### ISSUE THREAD

**Issue by jimanx2** [activemerchant/payment_icons#456]
Hello,

Our merchant requested us to list two payment icons (AXS and SAM). Please help to review these Pull Requests.

#454 #455 

Regards,
Haziman

**Comment by jimanx2** [comment]
Closing as both PR been merged

**Comment by jimanx2** [comment]
Hi @larouxn can i check when i can see both payment icons in the list of payment methods?

**Comment by larouxn** [comment]
@jimanx2, yes, I will report back here when you can expect to see then. Probably by end of next week, maybe sooner.

**Comment by jimanx2** [comment]
much appreciated!

**Comment by jimanx2** [comment]
Hi @larouxn sorry for coming back. Any news on this? Due to our merchant keeps asking.

**Comment by larouxn** [comment]
Hey @jimanx2, sorry I meant next week as in by June 25th, not this week.

**Comment by jimanx2** [comment]
I see, okay. I misread that. Thanks

**Comment by larouxn** [comment]
Update, we were able to release a new version of the gem ([v1.7.0](https://github.com/activemerchant/payment_icons/releases/tag/v1.7.0)) but it likely won't be live everywhere until some time next week.

**Comment by jimanx2** [comment]
> Update, we were able to release a new version of the gem ([v1.7.0](https://github.com/activemerchant/payment_icons/releases/tag/v1.7.0)) but it likely won't be live everywhere until some time next week.

I see. Thanks for the update. We will handle our merchant.

**Comment by larouxn** [comment]
👋 Hello @jimanx2, the icon(s) should be live now.

**Comment by jimanx2** [comment]
![image](https://user-images.githubusercontent.com/2503209/124101523-0510ce80-da92-11eb-9ace-4ef071cbe61a.png)

Oh yes! Appreciate your assistance both @larouxn and @tauthomas01 !
