### ISSUE TITLE
change payment method name "Yahoo mobile" to "Y!mobile) 

### ISSUE THREAD

**Issue by iwasakis** [activemerchant/payment_icons#459]
Hi @larouxn 

Would you correct the string of telco name  "Yahoo mobile (in Japanese ヤフーモバイル)"  to "Y!mobile (same in Japanese Y!mobile)"

 --"Yahoo mobile" is a mobile web portal provided by  "Yahoo Japan Corporation" 
 --"Y!mobile" is a brand of the mobile network provided by "Softbank Cooperation"

https://github.com/activemerchant/payment_icons/pull/277

Thanks,
Satoshi

**Comment by larouxn** [comment]
Hello @iwasakis, do you mean just updating the label? Like this https://github.com/activemerchant/payment_icons/pull/460?

**Comment by larouxn** [comment]
Hello @iwasakis, I'm seeing some issues with renaming to a name including `!`. If you can publish a PR that renames the `yahoo_mobile.svg` icon and manifest entry and achieves green CI, I'd be willing to review and potentially merge it.
https://github.com/activemerchant/payment_icons/blob/45da15340037403d0061cf1712125fa22d3713ef/db/payment_icons.yml#L733-L736

Additionally, if I Google "yahoo mobile" it actually returns many "Y!mobile" resources. 🤔

**Comment by iwasakis** [comment]
HI @larouxn,
I could not publish PR from some internal restriction, I would like to have your support.
In case when we cannot use exclamation marks, Ymobile also works.

Regarding your question, the second and third results are actually a page of "Ymobile" over "yahoo mobile" portal.

Please refer wikipedia JP for those two difference;
[Yahoo mobile]( https://ja.wikipedia.org/wiki/Yahoo!%E3%83%A2%E3%83%90%E3%82%A4%E3%83%AB)
[Y!mobile](https://ja.wikipedia.org/wiki/Y!mobile)

**Comment by larouxn** [comment]
👋 @iwasakis, how does this look? https://github.com/activemerchant/payment_icons/pull/462

**Comment by iwasakis** [comment]
@larouxn  Thank you so much for your all deployment effort, looks perfect!

**Comment by larouxn** [comment]
Released as part of [v1.7.0](https://github.com/activemerchant/payment_icons/releases/tag/v1.7.0) by the way.
