### ISSUE TITLE
Swish payment Icon goes blank on Mobile

### ISSUE THREAD

**Issue by Azzilx90** [activemerchant/payment_icons#510]
Merchant has pointed out that the Swish payment icon goes blank when viewed on a mobile device:

For internal use only: 
- Shopify Internal Ticket Number is **27242801**

 [![alt](https://screenshot.click/21-11-useas_einxt.png)](https://screenshot.click/21-11-useas_einxt.png)

**Comment by larouxn** [comment]
Closing this as I believe it was resolved via https://github.com/activemerchant/payment_icons/pull/512. Please reopen if otherwise.
