### ISSUE TITLE
Add Humm logo 

### ISSUE THREAD

**Issue by shophumm** [activemerchant/payment_icons#640]
Hey, 

Humm has a partnership with Shopify, and hummPaymentApp has approved and worked for months 

1, Need to reach out to add the Humm logo to the central library so that we could show/use it on the storefront checkout. The approved App name is hummPaymentApp 
Can you please add the below icon to the library to make them available as payment icons? 

![humm_BirdLogo_OrangeHigh (1)](https://user-images.githubusercontent.com/48002471/171800398-0ce9ab1c-25a6-436d-a60b-2eb70adf2149.jpg)

Thanks 
Roger

**Comment by larouxn** [comment]
👋 Hello @shophumm, can you please open a pull request to add the icon according to the [contribution guide](https://github.com/activemerchant/payment_icons/blob/3b558b771e1e096b8c4c23f0fef13f195563a19d/CONTRIBUTING.md)?

**Comment by rahilvirani** [comment]
The icons is [added](https://github.com/activemerchant/payment_icons/pull/709) and should be deployed to Shopify in the next release
