### ISSUE TITLE
Question about when our icons will be released

### ISSUE THREAD

**Issue by ecommerce-integrations** [activemerchant/payment_icons#781]
hi! hope you are well. I'd like to know if there is any ETA for releasing new icons? we submited ours a long time ago.
thanks for your help.

these are our PRs:

https://github.com/activemerchant/payment_icons/pull/742
https://github.com/activemerchant/payment_icons/pull/744
https://github.com/activemerchant/payment_icons/pull/743

kind regards

**Comment by Jacquesattaque** [comment]
Hoping to have a release before the end of next week. Thanks for your patience.
