### ISSUE TITLE
Adding PayPo payment icon

### ISSUE THREAD

**Issue by KasiaO-K** [activemerchant/payment_icons#792]
Please add a PayPo payment logotype.

![logo_PayPo_Kolor](https://user-images.githubusercontent.com/120580540/207819629-8dd24e04-dac8-49ce-9a21-368d105aa225.svg)
![PayPo_logo](https://user-images.githubusercontent.com/120580540/207819866-7471effc-6c8f-496d-ba13-d21b16de765d.png)

**Comment by Jacquesattaque** [comment]
Please follow [these instructions](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) to submit a new payment icon.

**Comment by adeniyiao** [comment]
This has been completed as per https://github.com/activemerchant/payment_icons/pull/803
