### ISSUE TITLE
Error occurs in Shopify store

### ISSUE THREAD

**Issue by ahmada3mar** [activemerchant/payment_icons#797]
Hello,
there are an issues when accessing shopify payment extension settings. 

The error said there is no catch payment inside the payments array. 

![image](https://user-images.githubusercontent.com/71763607/208845593-acee8d55-36f7-4dcb-82e3-c9e4edcfc729.png)

i checked the response, it's presents.

![image](https://user-images.githubusercontent.com/71763607/208845763-591dd051-bca9-49d7-9a7a-4cb4c52551f4.png)

**Comment by ahmada3mar** [comment]
@Jacquesattaque  your advice is highly appreciated.

**Comment by Jacquesattaque** [comment]
@ahmada3mar Are you still seeing this issue? We pushed out a release just before the holidays.

**Comment by ahmada3mar** [comment]
Hello @Jacquesattaque ,

Thanks for replying and happy new year.


Yes it's still occurring, the issue was showing when version 1.7.20 was released.

**Comment by Jacquesattaque** [comment]
@lunataoo May you have a look?

**Comment by douglas** [comment]
Hello folks! We're addressing this issue right now, ok? This is because `catch` is a reserved work in Javascript so we asked the developer of `catch` icon to change its name and I'm working on release a new version with the fix, ok?

**Comment by ahmada3mar** [comment]
Hello @douglas, thanks for replying.

Yes, I agree with you about the causes. it's completely agrees with my opinion .
thanks for your help.
