### ISSUE TITLE
Our Younited Pay Icon is still not showing in payment method options 

### ISSUE THREAD

**Issue by rafalen-dev** [activemerchant/payment_icons#823]
Hello @joshnuss 

We got the approval of https://github.com/activemerchant/payment_icons/pull/810 still our icon is not showing in list of payment options.
![image](https://user-images.githubusercontent.com/123946521/220075064-95709181-6ed5-442a-81c3-a38a532cb91c.png)

Thanks

**Comment by Jacquesattaque** [comment]
@adeniyiao Can you have a look?

**Comment by rafalen-dev** [comment]
@adeniyiao I remain at your disposal if you need my help.

**Comment by rafalen-dev** [comment]
@Jacquesattaque 

Please follow up on this issue as we are still pending to release our new payment extension with this Younited Pay icon.

Thanks.

**Comment by adeniyiao** [comment]
Hi @rafalen-dev, we are working on the deployment and should be released before end of the week.

**Comment by adeniyiao** [comment]
Hi @rafalen-dev , the icon is now deployed and now showing
![image](https://user-images.githubusercontent.com/97685764/220757551-29e68041-36a1-43b8-af48-c698c81fed57.png)

**Comment by rafalen-dev** [comment]
@adeniyiao Thanks for your respone, it's  working now.
