### ISSUE TITLE
The icon `EPS` is not showing up in merchant admin portal

### ISSUE THREAD

**Issue by chao-ding-awx** [activemerchant/payment_icons#827]
The icon `EPS` is not showing up in merchant admin portal even if the payment provide supports it.

**Comment by Jacquesattaque** [comment]
@adeniyiao Can you take a look? This isn't a new icon, seems strange that it's gone missing from the search in admin.

**Comment by adeniyiao** [comment]
Hi @chao-ding-awx , thanks for bringing it to our attention. We'll investigate this issue further and get back to you.

**Comment by adeniyiao** [comment]
Hi @chao-ding-awx ,

This issus is now resolved. Kindly check and confirm.
