### ISSUE TITLE
HSBC Logo not showing in Shopify checkout page

### ISSUE THREAD

**Issue by jeramay10** [activemerchant/payment_icons#834]
Hi, kindly check the hsbc logo is not showing up in checkout page when added as a payment method in our payment apps

<img width="550" alt="hsbc_logo_checkoutpage" src="https://user-images.githubusercontent.com/127072945/223017039-12686e87-fda5-41da-8455-bd9055787c45.png">

<img width="650" alt="hsbc_logo_payment setting" src="https://user-images.githubusercontent.com/127072945/223017061-8922afbf-488c-4ef9-acb0-338c57ffaedf.png">

**Comment by Jacquesattaque** [comment]
@adeniyiao Do you mind taking a look?

**Comment by adeniyiao** [comment]
Hi @jeramay10 thanks for bringing it to our attention. We'll investigate this issue further and get back to you.

**Comment by adeniyiao** [comment]
Hi @jeramay10 , this has been resolved. Kindly check and confirm

**Comment by jeramay10** [comment]
The HSBC logo is now visible @adeniyiao. Thanks!
