### ISSUE TITLE
Add Bank Transfer for overall online banking

### ISSUE THREAD

**Issue by HowKit** [activemerchant/payment_icons#898]
![bank-transfer-svgrepo-com](https://github.com/activemerchant/payment_icons/assets/140343053/15383961-263b-4d0e-9536-6f1d6d03f05d)

**Comment by Jacquesattaque** [comment]
This is a generic payment method, which we do not accept submissions for. We have an existing generic icon and have a task to create one for online banking in our backlog.

**Comment by Jacquesattaque** [comment]
@HowKit Sorry for the delay, we actually didn't have this publicly available. It's now available as `Generic`. We're hoping to add a proper bank transfer method in the near future as well.
