### ISSUE TITLE
Icons for MercadoPago / South America

### ISSUE THREAD

**Issue by reggi** [activemerchant/payment_icons#9]
Hello!

I've been looking into Hosted Payments with MercadoPago + Shopify and I found that many of the card icons are missing for the South American Credit Card companies.

There's a bit of copy on the Shopify Partners admin about adding icons to this lib.

![screen shot 2016-02-25 at 7 07 06 pm](https://cloud.githubusercontent.com/assets/296798/13338938/04597850-dbf3-11e5-827c-3a1e9beb32a8.png)

Here's a list I found here of South American credit card companies.

https://www.mercadopago.com.ar/developers/en/solutions/payments/custom-checkout/test-cards/test-local-cards/
- Naranja
- Hipercard
- Visa Débito
- Diners (Perhaps same as DinersClub?)
- Nativa Mastercard
- Mastercard Débito
- Tarjeta Shopping
- Elo
- Tarjeta MercadoPago
- Cencosud
- Cartão MercadoLivre
- Cabal
- Argencard

I'm unsure if MercadoPago itself should also have an Icon. Would a processor (similar to stripe) have an icon? I don't believe so. They just process the credit cards. However many of these companies do require you have a logo at checkout though.

Question is which of the above icons are y'all open to taking into this repo? All, some? I don't want to gather all the assets and then they don't get in. Thoughts?

[Just found this. MercadoPago already has a bunch of their cards](https://www.mercadopago.com/mla/com.mercadopago.web.landing.LandingController?id=banners#!institucionales)

![screen shot 2016-02-25 at 7 13 24 pm](https://cloud.githubusercontent.com/assets/296798/13339075/e8c8f56a-dbf3-11e5-912b-eb67f69acf30.png)

**Comment by andrewpaliga** [comment]
Hi @reggi we'll accept any icons that aren't already in the repo. Visa and Mastercard for example already  are listed. Keep in mind you can show a maximum of about 5 payment icons in Shopify checkout.

**Comment by AnthonyClark** [comment]
Hey @reggi, I'm going to close this off but if there's any of these icons you still want to add feel free to open a PR with them!
