### ISSUE TITLE
Add Deko Pay

### ISSUE THREAD

**Issue by moonpie2101** [activemerchant/payment_icons#901]
![dZfBj35Q](https://github.com/activemerchant/payment_icons/assets/140601201/03da7986-6389-4837-95bd-020b57311357)

Can we get the Deko logo added?

**Comment by Jacquesattaque** [comment]
Please follow our [contribution guidelines](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md) to get an icon added.
