### ISSUE TITLE
Add PostFinance Pay payment method logo

### ISSUE THREAD

**Issue by gutfa** [activemerchant/payment_icons#912]
Dear all,

We recently launched our new payment method PostFinance Pay which will replace our old payment methods PostFinance E-Finance and PostFinance Card: https://www.postfinance.ch/en/business/products/payment-collection/online-shop/postfinance-pay.html

The app is already available: https://apps.shopify.com/postfinance-pay

Please add the new payment method with the new icon to your central library:

Approved name: **PostFinance Pay**
Logo: 
![490_PF_Pay_logo](https://github.com/activemerchant/payment_icons/assets/71874723/dc9ac13f-624d-49fa-9e67-3cf3a20651b6)

You will find additional versions here: [postfinance_pay_logos (2).zip](https://github.com/activemerchant/payment_icons/files/12426263/postfinance_pay_logos.2.zip) or on our website: https://www.postfinance.ch/en/business/products/payment-collection/online-shop/postfinance-pay.html -> Documents and links -> Logo files.

Please let me know if you need any further details.

Thanks!
Fabian

**Comment by Jacquesattaque** [comment]
Please submit a PR to add the logo following our [contribution guidelines](https://github.com/activemerchant/payment_icons/blob/master/CONTRIBUTING.md).
