### ISSUE TITLE
Bitcoin Cash icon 

### ISSUE THREAD

**Issue by maximevaillancourt** [activemerchant/payment_icons#97]
The Bitcoin Cash icon is slightly different compared to the other icons.

![image](https://user-images.githubusercontent.com/8457808/41241832-f48577dc-6d6b-11e8-8ced-81fcdc5b8e19.png)

**Comment by stankostadinov** [comment]
Hey @maximevaillancourt 

I just wanted to update you that after [reporting](https://github.com/Shopify/themes/issues/157#issuecomment-396286236) the issue with the Bitcoin Cash icon, I actually went through all the icons in the repo and noticed this isn't the only icon with sharp edges, there are a few more like [arvato](https://github.com/activemerchant/payment_icons/blob/master/app/assets/images/payment_icons/arvato.svg) and [citadele](https://github.com/activemerchant/payment_icons/blob/master/app/assets/images/payment_icons/citadele.svg), so it might be worth checking all of them.

**Comment by stankostadinov** [comment]
It might be worth reviewing all the payment icons as it seems there are a few more with sharp edges like [arvato](https://github.com/activemerchant/payment_icons/blob/master/app/assets/images/payment_icons/arvato.svg) and [trustly](https://github.com/activemerchant/payment_icons/blob/master/app/assets/images/payment_icons/trustly.svg) for example.
